### PR TITLE
[WFSSL-88] Upgrade WildFly OpenSSL Natives to 2.2.0.Final and remove references to the linux-i386, windows-i386, and Solaris natives that are no longer produced

### PR DESCRIPTION
**Pull request by fjuma**
https://issues.redhat.com/browse/WFSSL-88
https://issues.redhat.com/browse/WFSSL-80
https://issues.redhat.com/browse/WFSSL-90

Also includes https://github.com/wildfly-security/wildfly-openssl/pull/110 which adds support for OpenSSL 3 so that can be tested together with the Natives upgrade.

### CODE REVIEW

**Comment by fjuma** [comment]
Just FYI, the current failures are due to the newly released WildFly OpenSSL Natives 2.2.0.Final not being found in Maven Central yet.

**Comment by fjuma** [comment]
@rmartinc I've updated the repositories in the pom.xml file to match what we have in the Elytron repo. So we're now past that previous error.

The next issue we're hitting in CI is:

```
Caused by: java.lang.UnsatisfiedLinkError: /home/runner/work/wildfly-openssl/wildfly-openssl/java/target/tmp-12315584110332453156openssl/libwfssl.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/runner/work/wildfly-openssl/wildfly-openssl/java/target/tmp-12315584110332453156openssl/libwfssl.so)
```

I don't see that locally because I have glibc 2.34 installed. Need to figure out how to update the version used by GitHub Actions VMs.

**Comment by rmartinc** [comment]
@fjuma That means that the compiled libwfssl depends on GLIBC_2.34, probably because GLIBC_3.24 redefined some methods that are used in the library. If you have access to the resulting `libwfssl.so` you can check the method and the version dependency doing:

```bash
objdump -T ./linux-x86_64/target/classes/linux-x86_64/libwfssl.so | grep GLIBC
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 free
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 strlen
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 printf
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 pthread_mutex_destroy
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 memset
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 fprintf
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 dlopen
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 pthread_mutex_unlock
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 malloc
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 realloc
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 memmove
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 getppid
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 exit
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 fwrite
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 dlsym
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 pthread_mutex_init
0000000000000000  w   DF *UND*	0000000000000000  GLIBC_2.2.5 __cxa_finalize
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 pthread_mutex_lock
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 dlerror
0000000000000000      DO *UND*	0000000000000000  GLIBC_2.2.5 stderr
```
For example in my case using GLIBC_2.3 all deps are 2.2.5.

I would try to compile with version < 2.34. I have checked and `dlopen` for example is redefined in 2.34. I would try to compile with a lower version of gclibc. That way the resulting `libwfssl.so` will depend on 2.2.5 only. Before distributing try to always check the dependencies with the objdump to see what gclibc the final library needs.

**Comment by fjuma** [comment]
Thanks, @rmartinc. I see the following when running that command:

```
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.34  dlerror
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 free
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 strlen
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 printf
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 pthread_mutex_destroy
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 memset
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.34  dlopen
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 fprintf
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 pthread_mutex_unlock
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 malloc
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 realloc
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 memmove
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.34  dlsym
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 getppid
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 exit
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 fwrite
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 pthread_mutex_init
0000000000000000  w   DF *UND*	0000000000000000  GLIBC_2.2.5 __cxa_finalize
0000000000000000      DF *UND*	0000000000000000  GLIBC_2.2.5 pthread_mutex_lock
0000000000000000      DO *UND*	0000000000000000  GLIBC_2.2.5 stderr
```

I recently upgraded to Fedora 35 so have 2.34 installed by default. I'll try compiling with a lower version.

**Comment by fjuma** [comment]
Thanks @rmartinc, I released a 2.2.0.SP01 version of the Linux native which was compiled with a lower glibc version and CI is passing now.

**Pull request merged**
