### PR TITLE
WFSSL-71 Do not use javax.security.cert.X509Certificate

### PR DESCRIPTION
**Pull request by tristantarrant**
https://issues.jboss..org/browse/WFSSL-71

### CODE REVIEW

**Review by fjuma — APPROVED** [review]

**Comment by fjuma** [comment]
https://github.com/wildfly-security/wildfly-openssl/pull/102 fixed the CI failures.

@tristantarrant Whenever you get a chance, if you could rebase this PR that would be great. The CI runs here don't seem to be picking up the latest changes for some reason. Thanks.

**Comment by tristantarrant** [comment]
rebased and repushed

**Comment by fjuma** [comment]
Thanks @tristantarrant!

@darranl This is ready for a second review. It looks like the macOS CI job is having trouble completing. We're not seeing this on other PRs. If you're able to, it might be good to try building this with your mac.

**Comment by darranl** [comment]
@fjuma FYI this is the logging I am seeing so far for the test that subsequently hangs:

https://gist.github.com/darranl/384be9283336ef07537fe2e3814494fa

I am not sure at the moment what options I have to add more logging if we need some more detail.

**Comment by darranl** [comment]
@fjuma I have added a thread dump I attempted to the gist but it is a bit corrupted as it wrote to STDOUT, I will try if i can run that test in isolation and see if I can attach my debugger.

**Comment by darranl** [comment]
After being able to easily reproduce the MacOS error here the build is now completing for me without error.  I am going to go ahead and merge the PRs and tag - if MacOS continues to play up it is not related to the recent changes.

**Pull request merged**
